version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: spoolman
      APP_PORT: 8000
    depends_on:
      - spoolman

  spoolman:
    image: ghcr.io/donkie/spoolman:latest
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${APP_DATA_DIR}/data
        target: /home/app/.local/share/spoolman
    environment:
      TZ: Europe/Stockholm
      user: "1000:1000"
      init: true