version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: dus-windows-arm_windows_1
      APP_PORT: 8006

  windows:
    image: dockurr/windows
    user: "1000:1000"
    container_name: windows
    environment:
      VERSION: "11"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
   volumes:
      - windows:/storage
    restart: always
    stop_grace_period: 2m

  volumes:
    windows:
      external: true